name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        image: ["gcc:13", "clang:16"]
        config: [Debug, Release]

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/think-cell/${{matrix.image}}

    steps:
    - uses: actions/checkout@v4
    - name: Setup Boost
      shell: bash
      run: |
        curl -L https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.zip --output boost_1_83_0.zip
        unzip -q boost_1_83_0.zip
        mv boost_1_83_0/ boost/

    - name: CMake configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DBoost_INCLUDE_DIR=$GITHUB_WORKSPACE/boost/ -DBoost_LIBRARY_DIR=$GITHUB_WORKSPACE/boost/

    - name: Compile
      run: cmake --build build
    - name: Run
      run: cmake --build build --target test
